// there are multiple ways to write functions in javascript

//Note: In Javascript while accessing doc using class , always remember that classes are only use for multiple childs or parents etc to access them in bulk so if you want to get only one node using class use [0] or [1] etc to select specifically.

// EVENTS: the change in the state of an object is know as event.
let btn1 = document.getElementsByClassName("btn1")[0];

// btn1.onclick=()=>{
//     console.log("Button was clicked");
//     document.body.style.backgroundColor = "red";
// }


// this is another alternative way 
// btn1.addEventListener("mouseover", function (e) { 
//     document.body.style.backgroundColor = "blue"
//     console.log("Target of event is:",e.target);
//     console.log("Type of event is:", e.type);
// })
// The event object(e) in JavaScript provides information about user actions on a webpage, such as clicks or key presses. It is automatically generated by the browser and passed to event handler functions, allowing developers to access details like event type, target element, and additional properties to respond to user interactions dynamically 
btn1.addEventListener("click",function(){
    // console.log(e);
    // console.log("Target of event is:",e.target);
    // console.log("Type of event is:", e.type);
    // console.log("The angle of X is:",e.clientX);
    // console.log("The angle of Y is:",e.clientY);
    console.log("Event 1 clicked");
})

const removesecondEvent = () => {
    console.log("Second Event ")
}
btn1.addEventListener("click", removesecondEvent);

// let suppose now we have to delele second event 
btn1.removeEventListener("click", removesecondEvent);


btn1.addEventListener("click", function () { 
  console.log("Third event clicked")
})
























